services:
  npm-publish:
    image: ghcr.io/williamjacksn/netlify-plugin-out-of-minutes-helper
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint:
      - /usr/local/bin/npm
      - publish
    environment:
      NPM_TOKEN:
