version: '3.8'

services:
  npm-publish:
    image: docker.pkg.github.com/williamjacksn/netlify-plugin-out-of-minutes/netlify-plugin-out-of-minutes-helper
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint:
      - /usr/local/bin/npm
      - publish
    environment:
      NPM_TOKEN:
