name: Publish NPM package

on:
  release:
    types:
      - published

jobs:

  publish:
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Publish the package
        run: docker-compose run -T npm-publish
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
